//
//  ChatViewModel.swift
//  Localight
//
//  Created by Timo Köthe on 07.07.25.
//

import Foundation
import FoundationModels

/// `ChatViewModel` is an observable class that manages the state and logic for a chat interface utilizing a language model session.
///
/// Responsibilities include:
/// - Managing user input and chat messages.
/// - Interfacing with `LanguageModelSession` to send prompts and handle responses.
/// - Tracking the status of responses and updating the UI accordingly.
///
/// Properties:
/// - `session`: Handles communication with the language model, initialized with specific instructions.
/// - `options`: Defines some runtime parameters of the model.
/// - `instructions`: Defines how the model should respond and behave (the active system prompt).
/// - `instructionsDraft`: The in-progress edit of the system prompt, applied to `instructions` only on confirmation.
/// - `temperature`: Defines the creativity of the model.
/// - `samplingMode`: Defines how the model chooses the next token in a response.
/// - `inputText`: The current text entered by the user.
/// - `prompt`: Stores the current prompt sent to the language model.
/// - `isResponding`: Indicates whether a response is currently being generated by the model.
/// - `isStreaming`: Indicates whether a response should be streamed to the UI or not.
/// - `messages`: The list of chat messages exchanged between the user and the model.
/// - `streamingResponse`: The current chunk of text for the UI of a streamed response by the model.
/// - `hasInstructionChanges`: Whether the draft holds a non-empty change relative to the active instructions.
///
/// Methods:
/// - `getResponse()`: Asynchronously sends the current prompt to the language model and appends both user and model messages to the chat, handling errors gracefully.
/// - `streamResponse()`: Asynchronously sends the current prompt to the language model and streams the models response to the chat while being generated, handling errors gracefully.
/// - `applyInstructions()`: Applies the edited draft as the new system prompt and rebuilds the session (clearing the chat).
/// - `resetSession()`: Resets the current language model session by setting all variables to their initial values.
@Observable class ChatViewModel {
    private var session: LanguageModelSession
    private var options: GenerationOptions

    var instructions: String        // The instructions to the model of how it should respond and behave.
    var instructionsDraft: String   // The in-progress edit of the system prompt, applied on confirmation.
    var temperature: Double         // The temperature to increase creativity.
    let contextSize: Int            // The model's maximum context size in tokens.
    var samplingMode: GenerationOptions.SamplingMode
    var inputText: String           // The text currently entered by the user.
    var prompt: String              // The finalized user input sent to the model.
    var isResponding: Bool          // Indicates whether the model is generating a response.
    var isStreaming: Bool           // Indicates whether a response should be streamed to the UI or not.
    var messages: [Message]         // A collection of all messages displayed in the chat view.
    var streamingResponse: String

    /// Whether the draft differs from the active instructions and is non-empty,
    /// i.e. whether there is a meaningful system prompt change to apply.
    var hasInstructionChanges: Bool {
        let trimmed = instructionsDraft.trimmingCharacters(in: .whitespacesAndNewlines)
        return !trimmed.isEmpty && trimmed != instructions
    }

    /// Initializes all variables with their values.
    init() {
        let defaultInstructions = "Act as the best buddie. Keep your answer short."
        self.session = LanguageModelSession(instructions: defaultInstructions)
        self.options = GenerationOptions(samplingMode: .greedy, temperature: 2.0)
        self.instructions = defaultInstructions
        self.instructionsDraft = defaultInstructions
        self.temperature = 2.0
        self.contextSize = SystemLanguageModel.default.contextSize
        self.samplingMode = .greedy
        self.inputText = ""
        self.prompt = ""
        self.isResponding = false
        self.isStreaming = false
        self.messages = []
        self.streamingResponse = ""
    }
    
    /// Generates a response from the model based on the user’s current input.
    ///
    /// This function handles the full request–response cycle:
    /// - Marks the view as busy (`isResponding = true`)
    /// - Appends the user’s input as a message to be shown on the ChatView
    /// - Sends the finalized prompt to the model
    /// - Awaits the model’s response, or an error message if the request fails
    /// - Resets the state to indicate the response cycle has finished
    func getResponse() async {
        isResponding = true
        messages.append(Message(text: inputText, sender: .user))
        prompt = inputText
        inputText = ""
        do {
            let response = try await session.respond(to: prompt)
            let message = Message(text: response.content, sender: .model)
            messages.append(message)
        } catch {
            let message = Message(text: error.localizedDescription, sender: .model)
            messages.append(message)
        }
        isResponding = false
    }
    
    /// Streams a response from the model based on the user’s current input.
    ///
    /// This function handles the full request–response cycle:
    /// - Marks the view as busy (`isResponding = true`)
    /// - Appends the user’s input as a message to be shown on the ChatView
    /// - Sends the finalized prompt to the model
    /// - Streams the model’s response, or appends an error message if the request fails
    /// - Resets the state to indicate the response cycle has finished
    func streamResponse() async {
        isResponding = true
        messages.append(Message(text: inputText, sender: .user))
        prompt = inputText
        inputText = ""
        let stream = session.streamResponse(to: prompt)
        do {
            for try await chunk in stream {
                self.streamingResponse = chunk.content
            }
            
            let response = try await stream.collect()
            let message = Message(text: response.content, sender: .model)
            messages.append(message)
        } catch {
            let message = Message(text: error.localizedDescription, sender: .model)
            messages.append(message)
        }
        streamingResponse = ""
        isResponding = false
    }
    
    /// Applies the edited draft as the new system prompt.
    ///
    /// Foundation Models fixes a session’s instructions at creation time, so a new system
    /// prompt requires a fresh session. This function trims and promotes the draft to the
    /// active `instructions`, keeps the draft in sync, and rebuilds the session via
    /// `resetSession()` — which also clears the current chat.
    func applyInstructions() {
        let trimmed = instructionsDraft.trimmingCharacters(in: .whitespacesAndNewlines)
        instructions = trimmed
        instructionsDraft = trimmed
        resetSession()
    }

    /// Resets the current session to initial values.
    ///
    /// This function resets the current session by reseting all variables to their initial values.
    func resetSession() {
        self.session = LanguageModelSession(instructions: self.instructions)
        self.options = GenerationOptions(samplingMode: .greedy, temperature: self.temperature)
        self.inputText = ""
        self.prompt = ""
        self.isResponding = false
        self.isStreaming = false
        self.messages = []
        self.streamingResponse = ""
    }
}
